### ISSUE TITLE
how to modify dhid?

### ISSUE THREAD

**Issue by zhumingyu** [Zke1ev3n/WiFiMaster#1]
Hey,guy!
    how to modify dhid?thks

**Comment by Zke1ev3n** [comment]
这个是设备标识，具体的生成算法我没有去逆，你可以安装一次wifi万能钥匙然后去sharedpreference里获得这个值。

**Comment by zhumingyu** [comment]
LZ，有没有测试利用此值具体查询多少次后易被ban?

**Comment by Zke1ev3n** [comment]
这个一般不会因为次数被ban，如果短时间发起大量的请求容易被ban。

**Comment by zhumingyu** [comment]
@Zke1ev3n thks
